# Generated by Django 4.0.6 on 2022-07-12 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
